// +build !noasm
// Generated by PeachPy 0.2.0 from roll_hash.py


// func rollHashASM(f1 uintptr, f2 uint32) uint32
TEXT ·rollHashASM(SB),4,$0-16
	MOVQ f1+0(FP), DX
	MOVL f2+8(FP), BX
	MOVWLZX 24(DX), CX
	MOVWLZX 28(DX), DI
	MOVWLZX 32(DX), SI
	MOVWLZX 36(DX), BP
	SUBL CX, DI
	ADDL $7, R8
	MULL BX
	ADDL R8, DI
	ADDL BX, CX
	ADDL $1, BP
	ADDL DI, CX
	ADDL SI, CX
	MOVL CX, ret+12(FP)
	RET
