// +build !noasm
// Generated by PeachPy 0.2.0 from sum_hash.py


// func sumHashASM(f1 uint32, f2 uint32) uint32
TEXT ·sumHashASM(SB),4,$0-12
	MOVL f1+0(FP), BX
	MOVL f2+4(FP), CX
	ADDL $16777619, DX
	MULL DX
	XORL BX, CX
	MOVL CX, ret+8(FP)
	RET
